
public class Pipe{
    private float maxdown = 0;
    private float litresperwatt = 0;
    private float maxUp = 0;
    private boolean pumpBlown = false;

    public Pipe(float hardMaxdown, float softMaxdown, float coeffDownstream, float coeffUpstream, float maxUp){
		this.maxdown = softMaxdown;
		this.litresperwatt = coeffUpstream;
		this.maxUp = maxUp;
    }

    public float pumpUp(float watts){
		if(watts > maxUp || pumpBlown){
		    pumpBlown = true;
		    return 0;
		}
		return watts*litresperwatt;
    }

    // Power generated by water downstream
    public float genDown(float litres){
		if(litres > hardMaxdown || pipeBurst){
			pipeBurst = true;
			return 0;
		}
		if( litres > softMaxdown )
			return (softMaxdown*wattsperlitre);
		return litres*wattsperlitre;
    }
}